import { Bell, Camera, Check, LockKeyhole, Moon, Sun } from 'lucide-react'
import { useState } from 'react'
import toast from 'react-hot-toast'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

const Toggle = ({ checked, onChange }: { checked: boolean; onChange: () => void }) => <button type="button" onClick={onChange} className={`relative h-6 w-11 rounded-full transition ${checked ? 'bg-blue-600' : 'bg-slate-200'}`} aria-pressed={checked}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${checked ? 'left-6' : 'left-1'}`}/></button>
export function ProfilePage() { const [saving, setSaving] = useState(false); const save = async () => { setSaving(true); await new Promise((r) => setTimeout(r, 400)); setSaving(false); toast.success('Profile updated') }; return <div className="mx-auto max-w-3xl"><div><p className="text-sm font-semibold text-blue-600">PERSONAL SPACE</p><h2 className="heading mt-1 text-3xl font-extrabold">Your profile</h2><p className="mt-2 text-sm text-slate-500">Manage how you appear across the workspace.</p></div><section className="surface mt-7 p-5 sm:p-7"><div className="flex items-center gap-4 border-b border-slate-100 pb-6"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-400 text-lg font-extrabold text-white">AM</span><div><button className="inline-flex items-center gap-2 text-sm font-bold text-blue-600"><Camera size={16}/> Change photo</button><p className="mt-1 text-xs text-slate-500">JPG, PNG or WEBP. 2MB max.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Input label="First name" defaultValue="Amelia"/><Input label="Last name" defaultValue="Morgan"/><Input label="Work email" defaultValue="amelia@taskflow.io" type="email"/><Input label="Role" defaultValue="Product designer"/></div><div className="mt-6"><label className="text-sm font-semibold text-slate-700">Bio</label><textarea defaultValue="Designing calm, intuitive experiences for complex work." className="mt-2 min-h-24 w-full rounded-xl border p-3 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10"/></div><div className="mt-6 flex justify-end border-t border-slate-100 pt-5"><Button loading={saving} onClick={save}><Check size={17}/> Save profile</Button></div></section></div> }
export function SettingsPage() { const [email, setEmail] = useState(true); const [push, setPush] = useState(false); const [dark, setDark] = useState(() => localStorage.getItem('taskflow-theme') === 'dark'); const theme = () => { const next = !dark; setDark(next); localStorage.setItem('taskflow-theme', next ? 'dark' : 'light'); document.documentElement.classList.toggle('dark', next); toast.success(`${next ? 'Dark' : 'Light'} mode enabled`) }; return <div className="mx-auto max-w-3xl"><div><p className="text-sm font-semibold text-blue-600">PREFERENCES</p><h2 className="heading mt-1 text-3xl font-extrabold">Settings</h2><p className="mt-2 text-sm text-slate-500">Fine-tune your TaskFlow experience.</p></div><div className="mt-7 space-y-5"><section className="surface p-5 sm:p-7"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><Bell size={19}/></span><div><h3 className="heading font-extrabold">Notifications</h3><p className="text-sm text-slate-500">Choose how we keep you in the loop.</p></div></div><div className="mt-6 divide-y"><div className="flex items-center justify-between py-4"><div><p className="text-sm font-bold">Email updates</p><p className="mt-1 text-xs text-slate-500">Daily summary and mentions</p></div><Toggle checked={email} onChange={() => setEmail(!email)}/></div><div className="flex items-center justify-between py-4"><div><p className="text-sm font-bold">Push notifications</p><p className="mt-1 text-xs text-slate-500">Important task activity</p></div><Toggle checked={push} onChange={() => setPush(!push)}/></div></div></section><section className="surface p-5 sm:p-7"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-500">{dark ? <Moon size={19}/> : <Sun size={19}/>}</span><div><h3 className="heading font-extrabold">Appearance</h3><p className="text-sm text-slate-500">Use a darker color theme.</p></div></div><Toggle checked={dark} onChange={theme}/></div></section><section className="surface p-5 sm:p-7"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-600"><LockKeyhole size={19}/></span><div><h3 className="heading font-extrabold">Security</h3><p className="text-sm text-slate-500">Password and account protection.</p></div></div><Button variant="secondary" className="mt-5">Change password</Button></section></div></div> }
